# Generated by Django 4.1.3 on 2022-11-20 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_alpha_cares_about', models.FloatField()),
                ('country_alpha_no_nukes', models.FloatField()),
                ('country_alpha_agression', models.FloatField()),
                ('country_alpha_international_rep', models.FloatField()),
                ('country_alpha_population', models.FloatField()),
                ('country_beta_cares_about', models.FloatField()),
                ('country_beta_no_nukes', models.FloatField()),
                ('country_beta_agression', models.FloatField()),
                ('country_beta_international_rep', models.FloatField()),
                ('country_beta_population', models.FloatField()),
                ('provocation', models.FloatField()),
                ('ai_result', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressed', models.BooleanField()),
                ('params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.paramset')),
            ],
        ),
    ]
